### ISSUE TITLE
Update proxyUrl docs to mention HTTPS is fine and to also talk about the env vars you can set

### ISSUE THREAD

**Issue by zionts** [apollographql/engine-docs#171]

**Comment by qubusp** [comment]
Same problem here - trying to fine tune proxy engine on local and fine tune stuff - not able to parse 
env 

```
version: '3.3'
services:
  boom:
    image: gcr.io/mdg-public/engine:1.0.6
    env_file:
      - ./env
    links:
      - nginx
  nginx:
    image: interceptor
    ports:
      - 80:80

```
